site_name: Gandalf Docs
theme:
  name: material
nav:
  - Home: index.md
  - API: reference/
plugins:
- search
- gen-files:
    scripts:
      - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings